# Generated by Django 5.0.6 on 2024-07-22 07:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_visit", "0005_remove_uservisit_session_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservisit",
            name="hash",
        ),
    ]
