# Generated by Django 5.0.6 on 2024-07-22 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_visit", "0006_remove_uservisit_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uservisit",
            name="context",
        ),
    ]
