# Generated by Django 5.0.6 on 2024-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="profile_image",
            field=models.ImageField(
                default="profile_images/default.jpg", upload_to="profile_images/"
            ),
        ),
    ]
