# Generated by Django 5.0.6 on 2024-06-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="sentences",
            field=models.ManyToManyField(to="main.sentences"),
        ),
        migrations.RemoveField(
            model_name="questions",
            name="title",
        ),
        migrations.AddField(
            model_name="questions",
            name="title",
            field=models.CharField(default="Pregunta", max_length=150),
            preserve_default=False,
        ),
    ]
