# Generated by Django 5.0.6 on 2024-06-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_questions_sentences_remove_questions_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="complete",
            field=models.BooleanField(default=0),
        ),
    ]
