# Generated by Django 5.0.6 on 2024-07-11 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_assignments_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentassignments",
            name="title",
        ),
        migrations.RemoveField(
            model_name="studentassignments",
            name="topics",
        ),
        migrations.AddField(
            model_name="studentassignments",
            name="assignments",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.assignments",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="studentquestion",
            name="assignments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.studentassignments",
            ),
        ),
    ]
