# Generated by Django 5.0.6 on 2024-07-11 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_studentassignments_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentquestion",
            name="assignments",
        ),
        migrations.AddField(
            model_name="questions",
            name="assignments",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.assignments",
            ),
            preserve_default=False,
        ),
    ]
