# Generated by Django 5.0.6 on 2024-06-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_assignments_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="questions",
            name="complete",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
