# Generated by Django 5.0.6 on 2024-06-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_questions_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignments",
            name="complete",
            field=models.SmallIntegerField(),
        ),
    ]
