# Generated by Django 5.0.6 on 2024-06-23 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_assignments_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignments",
            old_name="complete",
            new_name="completed",
        ),
        migrations.AlterField(
            model_name="questions",
            name="assignments",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="main.assignments",
            ),
        ),
    ]
