# Generated by Django 5.1 on 2024-10-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_classschedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day_of_week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="classschedule",
            name="day_of_week",
        ),
        migrations.AddField(
            model_name="classschedule",
            name="day_of_week",
            field=models.ManyToManyField(to="main.day_of_week"),
        ),
    ]
