# Generated by Django 5.1 on 2024-10-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_day_of_week_remove_classschedule_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day_of_week",
            name="title",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ]
            ),
        ),
    ]
