# Generated by Django 5.1 on 2024-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_alter_day_of_week_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.ManyToManyField(
                blank=True, related_name="answer", to="main.choices"
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="sentences",
            field=models.ManyToManyField(blank=True, to="main.sentences"),
        ),
    ]
