# Generated by Django 5.1 on 2024-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_questions_answer_alter_questions_sentences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="answer", to="main.choices"
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="sentences",
            field=models.ManyToManyField(blank=True, null=True, to="main.sentences"),
        ),
    ]
