# Generated by Django 5.1 on 2024-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_questions_answer_alter_questions_sentences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.ManyToManyField(
                blank=True, related_name="answer", to="main.choices"
            ),
        ),
        migrations.AlterField(
            model_name="questions",
            name="sentences",
            field=models.ManyToManyField(blank=True, to="main.sentences"),
        ),
        migrations.AlterField(
            model_name="students",
            name="profile_image",
            field=models.FileField(
                default="profileimages00/defaultImgProfile.png",
                upload_to="profileimages00/",
            ),
        ),
    ]
