# Generated by Django 5.1 on 2024-11-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_students_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="profile_image",
            field=models.ImageField(
                default="profileimages0/defaultImgProfile.png",
                upload_to="profileimages0/",
            ),
        ),
    ]
